config/routes.rb
Rails.application.routes.draw do
  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" 
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider
      
  get "up" => "rails/health#show", as: :rails_health_check

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  root 'welcome#index'

  resources :welcome
  resources :users
  resources :password_resets, only: %i[new create edit update]
  resources :posts do
    collection do
      get 'search', to: 'posts#search', as: :search
    end
    resources :post_details, shallow: true do
      collection do
        get 'publish'
      end
    end
    resources :comments, only: %i[create destroy]
    resource :likes, only: %i[create destroy show]
  end

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  get 'terms_of_service', to: 'pages#terms_of_service'
  get 'privacy', to: 'pages#privacy'
end
  

app/models/post_detail.rb
class PostDetail < ApplicationRecord
  belongs_to :post

  validates :body, presence: true
  validates :arrival_at, presence: true
  validate :place_name, :address
  validates :post_id, presence: true

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  mount_uploader :image, PostDetailImageUploader
end

app/controllers/post_details_controller.rb
class PostDetailsController < ApplicationController
  def index
    @post_details = PostDetail.all.includes(:post).order(arrival_at: :asc)
  end

  def new
    @post = Post.find(params[:post_id])
    @post_details = @post.post_details.order(arrival_at: :asc)
    @post_detail = PostDetail.new
  end

  def create
    @post_detail = PostDetail.new(post_detail_params)
    @post = @post_detail.post
  
    if @post_detail.arrival_at.present?
      @post_detail.arrival_at = DateTime.new(@post.departure_date.year, @post.departure_date.month, @post.departure_date.day,
                                              @post_detail.arrival_at.hour, @post_detail.arrival_at.min, @post_detail.arrival_at.sec)
    end

    if @post_detail.latitude.nil?
      @post_detail.address = nil
    end

    if @post_detail.save
      @post_details = @post_detail.post.post_details.order(arrival_at: :asc)
      @post_detail = PostDetail.new

      respond_to do |format|
        format.html { redirect_to post_post_details_path(@post), notice: t('.success') }
        format.turbo_stream
      end
    else
      respond_to do |format|
        format.html { redirect_to post_post_details_path(@post), danger: t('.failure'), status: :unprocessable_entity }
        format.turbo_stream
      end
    end
  end
  
  def update; end

  def show
    @post_detail = PostDetail.find(params[:id])
  end

  def destroy
    @post_detail = PostDetail.find(params[:id])
    @post_detail.destroy!

    @post_details = @post_detail.post.post_details.order(arrival_at: :asc)

    respond_to do |format|
      format.html { redirect_to post_path(@post_detail.post), notice: t('.success') }
      format.turbo_stream
    end
  end

  def publish
    @post = Post.find(params[:post_id])
    @post.status = 1

    if @post.save
      redirect_to post_path(@post), success: t('.success')
    else
      flash.now[:danger] = t('.failure')
      render :preview, status: :unprocessable_entity
    end
  end

  private

  def post_detail_params
    params.require(:post_detail).permit(:body, :arrival_at, :image, :image_cache, :place_name, :address, :latitude, :longitude).merge(post_id: params[:post_id])
  end
end

app/helpers/post_details_helper.rb
module PostDetailsHelper
end

app/views/post_details/_form.html.erb
<%= form_with(model: [post, post_detail], data: { turbo: true }) do |f| %>
  <%= render 'shared/error_messages', object: post_detail %>
  <div class="nested-fields bg-secondary-subtle rounded-3">
    <div class="pt-3">
      <h2 class="fw-bold fs-4 text-center">行き先追加</h2>
    </div>
      <div class="m-3">
        <%= f.label :body, "本文 [必須]" %>
        <%= f.text_area :body, class: "form-control" %>
      </div>
      <div class="m-3">
        <%= f.label :arrival_at, "到着時間 [必須]"  %>
        <%= f.time_field :arrival_at, class: "form-control" %>
      </div>
      <div class="m-3">
        <%= f.label :image %>
        <%= f.file_field :image, class: "form-control", accept: 'image/*' %>
        <%= f.hidden_field :image_cache %>
      </div>
      <div class="m-3">
        <%= f.hidden_field :place_name, id: 'place_name' %>
        <%= f.hidden_field :latitude, id: 'latitude' %>
        <%= f.hidden_field :longitude, id: 'longitude' %>
        <%= f.label :address, for: 'pac-input' %>
        <%= f.text_field :address, id: "pac-input", class: "form-control", placeholder: "検索" %>
        <div class="m-3" id='map' style="height: 400px;"></div>
      </div>
      <div class="d-grid gap-2 col-6 mx-auto my-2 pb-3">
        <%= f.submit "追加", class: "btn btn-dark", id: "add-post_detail" %>
      </div>
  </div>
<% end %>

app/views/post_details/_post_detail.html.erb
<tr id="post_detail-<%= post_detail.id %>">
  <td style="white-space: normal;">
    <h3 class="small"><%= l post_detail.arrival_at, format: :shorttime %></h3>
  </td>
  <td style="white-space: normal;">
    <%= simple_format(post_detail.body) %>
    <% if post_detail.address.present? %>
      <h4 class="small">&#x1F4CD; <%= post_detail.place_name %></h4>
    <% end %>
    <% if post_detail.image.present? %>
      <%= image_tag post_detail.image.url, width: "200", height: "200", style: "object-fit: cover;", class: "rounded img-responsive text-center" %>
    <% end %>
  </td>
  <% if action_type == :new %>
    <td class="action" style="white-space: normal;">
      <ul class="list-inline justify-content-center" style="float: right;">
        <li class="list-inline-item">
          <%= link_to "削除", post_detail_path(post_detail), class: "btn btn-danger", id: "button-delete-#{post_detail.id}", method: :delete, data: { turbo_method: :delete, turbo_confirm: '行き先を削除します。よろしいですか？' } %>
        </li>
      </ul>
    </td>
  <% end %>
</tr>

app/views/post_details/create.turbo_stream.erb
<% if @post_detail.errors.present? %>
  <%= turbo_stream.replace "post_detail-form" do %>
    <div id="post_detail-form">
      <%= render 'post_details/form', post_detail: @post_detail, post: @post %> 
    </div>
    <script>
      function initMap() {
        var map = new google.maps.Map(document.getElementById("map"), {
          center: { lat: 35.6803997, lng: 139.7690174 },
          zoom: 15,
          mapTypeId: "roadmap",
        });
        var input = document.getElementById("pac-input");
        var searchBox = new google.maps.places.SearchBox(input);
      
        var markers = [];
      
        searchBox.addListener("places_changed", () => {
          var places = searchBox.getPlaces();
      
          if (places.length == 0) {
            return;
          }
      
          markers.forEach((marker) => {
            marker.setMap(null);
          });
          markers = [];
      
          var bounds = new google.maps.LatLngBounds();
      
          places.forEach((place) => {
            if (!place.geometry || !place.geometry.location) {
              console.log("Returned place contains no geometry");
              return;
            }
      
            markers.push(
              new google.maps.Marker({
                map,
                position: place.geometry.location
              }),
            );
            if (place.geometry.viewport) {
              bounds.union(place.geometry.viewport);
            } else {
              bounds.extend(place.geometry.location);
            }
      
            document.getElementById('place_name').value = place.name;
            document.getElementById('latitude').value = place.geometry.location.lat();
            document.getElementById('longitude').value = place.geometry.location.lng();
          });
          map.fitBounds(bounds);
        });
      };

      initMap();
    </script>
  <% end %>
<% else %>
  <%= turbo_stream.replace "table-post_detail" do %>
    <tbody id="table-post_detail">
      <%= render @post_details, action_type: :new %>
    </tbody>
  <% end %>
  <%= turbo_stream.replace "post_detail-form" do %>
    <div id="post_detail-form">
      <%= render 'post_details/form', post_detail: @post_detail, post: @post %> 
    </div>
    <script>
      function initMap() {
        var map = new google.maps.Map(document.getElementById("map"), {
          center: { lat: 35.6803997, lng: 139.7690174 },
          zoom: 15,
          mapTypeId: "roadmap",
        });
        var input = document.getElementById("pac-input");
        var searchBox = new google.maps.places.SearchBox(input);
      
        var markers = [];
      
        searchBox.addListener("places_changed", () => {
          var places = searchBox.getPlaces();
      
          if (places.length == 0) {
            return;
          }
      
          markers.forEach((marker) => {
            marker.setMap(null);
          });
          markers = [];
      
          var bounds = new google.maps.LatLngBounds();
      
          places.forEach((place) => {
            if (!place.geometry || !place.geometry.location) {
              console.log("Returned place contains no geometry");
              return;
            }
      
            markers.push(
              new google.maps.Marker({
                map,
                position: place.geometry.location
              }),
            );
            if (place.geometry.viewport) {
              bounds.union(place.geometry.viewport);
            } else {
              bounds.extend(place.geometry.location);
            }
      
            document.getElementById('place_name').value = place.name;
            document.getElementById('latitude').value = place.geometry.location.lat();
            document.getElementById('longitude').value = place.geometry.location.lng();
          });
          map.fitBounds(bounds);
        });
      };

      initMap();
    </script>
  <% end %>
<% end %>

app/views/post_details/destroy.turbo_stream.erb
<%= turbo_stream.remove "post_detail-#{@post_detail.id}" %>
<% if @post_details.any? %>
  <%= turbo_stream.replace "table-post_detail" do %>
    <tbody id="table-post_detail">
      <%= render @post_details, action_type: :new %>
    </tbody>
  <% end %>
<% else %>
  <%= turbo_stream.replace "table-post_detail" do %>
    <tbody id="table-post_detail">
      <tr id="post_detail">
        <td>
          <p class="text-center p-3">まだ行き先が追加されていません</p>
        </td>
      </tr>
    </tbody>
  <% end %>
<% end %>

app/views/post_details/new.html.erb
<% content_for(:title, @post.title) %>
<div class="container pt-3">
  <div class="row">
    <div class="col-lg-9 offset-lg-2 my-5">
      <h1 class="fw-bold fs-3 text-center">新規投稿作成</h1>
      <% if @post.image.present? %>
        <div class="text-center ratio ratio-16x9 mb-4">
          <%= image_tag @post.image.url, width: "100%", height: "auto", style: "object-fit: cover;", class: "img-fluid" %>
        </div>
      <% end %>
      <h3 style="display: inline;" class="fw-bold"><%= @post.title %></h3>
      <ul class="list-inline">
        <li class="list-inline-item"><%= "by #{@post.user.name}" %></li>
        <li class="list-inline-item text-secondary"><%= l(@post.created_at, format: :time)%></li>
      </ul>
      <p class="fw-bold fs-5"><%= l @post.departure_date %></p>
      <div class="table-responsive">
        <table class="table">
          <tbody id="table-post_detail">
            <% if @post_details != nil && @post_details.any? %>
              <%= render @post_details, action_type: :new %>
            <% else %>
              <tr id="post_detail">
                <td>
                  <p class="text-center p-3">まだ行き先が追加されていません</p>
                </td>
              </tr>
            <% end %>      
          </tbody>
        </table>
      </div>
      <div id="post_detail-form">
        <%= render 'post_details/form', post_detail: @post_detail, post: @post %>
      </div>
      <div class="d-grid gap-2 col-6 mx-auto my-2">
        <%= link_to "記事を投稿する", publish_post_post_details_path, class: "btn btn-success", data: { turbo_method: "get", turbo_confirm: "記事を投稿します。よろしいですか？" } %>
      </div>
      <div class="d-grid gap-2 col-6 mx-auto my-2">
        <%= link_to "キャンセル", posts_path, class: "btn btn-outline-secondary" %>
      </div>
    </div>
  </div>
</div>
<script>
  function initMap() {
    var map = new google.maps.Map(document.getElementById("map"), {
      center: { lat: 35.6803997, lng: 139.7690174 },
      zoom: 15,
      mapTypeId: "roadmap",
    });
    var input = document.getElementById("pac-input");
    var searchBox = new google.maps.places.SearchBox(input);

    var markers = [];

    searchBox.addListener("places_changed", () => {
      var places = searchBox.getPlaces();

      if (places.length == 0) {
        return;
      }

      markers.forEach((marker) => {
        marker.setMap(null);
      });
      markers = [];

      var bounds = new google.maps.LatLngBounds();

      places.forEach((place) => {
        if (!place.geometry || !place.geometry.location) {
          console.log("Returned place contains no geometry");
          return;
        }

        markers.push(
          new google.maps.Marker({
            map,
            position: place.geometry.location
          }),
        );
        if (place.geometry.viewport) {
          bounds.union(place.geometry.viewport);
        } else {
          bounds.extend(place.geometry.location);
        }

        document.getElementById('place_name').value = place.name;
        document.getElementById('latitude').value = place.geometry.location.lat();
        document.getElementById('longitude').value = place.geometry.location.lng();
      });
      map.fitBounds(bounds);
    });
  };
</script>