config/routes.rb
Rails.application.routes.draw do
  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" 
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider
      
  get "up" => "rails/health#show", as: :rails_health_check

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  root 'welcome#index'

  resources :welcome
  resources :users
  resources :password_resets, only: %i[new create edit update]
  resources :posts do
    collection do
      get 'search', to: 'posts#search', as: :search
    end
    resources :post_details, shallow: true do
      collection do
        get 'publish'
      end
    end
    resources :comments, only: %i[create destroy]
    resource :likes, only: %i[create destroy show]
  end

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  get 'terms_of_service', to: 'pages#terms_of_service'
  get 'privacy', to: 'pages#privacy'
end
  

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true, length: { maximum: 65_535 }
  validates :user_id, presence: true
  validates :post_id, presence: true

  belongs_to :user
  belongs_to :post
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = current_user.comments.build(comment_params)
    @comment.save
    @comments = @comment.post.comments.includes(:user).order(created_at: :desc)
  end

  def destroy
    @comment = current_user.comments.find(params[:id])
    @comment.destroy!
    @comments = @comment.post.comments.includes(:user).order(created_at: :desc)
    respond_to do |format|
      format.html { redirect_to post_path(@comment.post) }
      format.turbo_stream
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body).merge(post_id: params[:post_id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<tr id="comment-<%= comment.id %>">
  <td>
    <ul class="list-inline d-flex mb-1">
      <li class="list-inline-item">
        <%= link_to user_path(comment.user), class: "link-body-emphasis link-underline link-underline-opacity-0 link-underline-opacity-75-hover" do %>
          <%= image_tag comment.user.avatar_url, class: 'rounded-circle mr15', width: '20', height: '20' %>
          <%= "#{comment.user.name}" %>
        <% end %>
      </li>
      <li class="list-inline-item">
        <h3 class="small d-inline text-secondary"><%= l(comment.created_at, format: :time) %></h3>
      </li>
    </ul>
    <p><%= simple_format(comment.body) %></p>
  </td>
  <td class="action">
    <% if !current_user.nil? && current_user.own?(comment) %>
      <ul class="list-inline justify-content-center" style="float: right;">
        <li class="list-inline-item">
          <%= link_to "削除", post_comment_path(comment.post, comment), class: "btn btn-danger", id: "button-comment-delete-#{comment.id}", data: { turbo_method: :delete, turbo_confirm: "コメントを削除します。よろしいですか？" } %>
        </li>
      </ul>
    <% end %>
  </td>
</tr>

app/views/comments/_form.html.erb
<div id="comment-form">
  <%= form_with model: comment, url: post_comments_path(post) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <%= f.label :body, class: "fw-bold mb-2" %>
    <% if !current_user.nil? %>
      <%= f.text_area :body, class: "form-control mb-3", row: "4", placeholder: Comment.human_attribute_name(:body) %>
    <% else %>
      <%= f.text_area :body, class: "form-control mb-3", row: "4", placeholder: "ログイン後、コメントが可能になります", disabled: true %>
    <% end %>
    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
    <% if !current_user.nil? %>
      <%= f.submit t('helpers.submit.post'), class: "btn btn-dark" %>
    <% else %>
      <%= f.submit t('helpers.submit.post'), class: "btn btn-dark", disabled: true %>
    <% end %>
    </div>
  <% end %>
</div>

app/views/comments/create.turbo_stream.erb
<% if @comment.errors.present? %>
  <%= turbo_stream.replace "comment-form" do %>
    <%= render 'comments/form', comment: @comment, post: @comment.post %>
  <% end %>
<% else %>
  <%= turbo_stream.prepend "table-comment" do %>
    <%= render 'comments/comment', comment: @comment %>
  <% end %>
  <%= turbo_stream.replace "comment-form" do %>
    <%= render 'comments/form', comment: Comment.new, post: @comment.post %>
  <% end %>
  <%= turbo_stream.replace "comment-count" do %>
    <p class="fw-bold", id="comment-count"><%= @comments.count %>件のコメント</p>
  <% end %>
<% end %>

app/views/comments/destroy.turbo_stream.erb
<%= turbo_stream.remove "comment-#{@comment.id}" %>

<%= turbo_stream.replace "comment-count" do %>
  <p class="fw-bold", id="comment-count"><%= @comments.count %>件のコメント</p>
<% end %>