config/routes.rb
Rails.application.routes.draw do
  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" 
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider
      
  get "up" => "rails/health#show", as: :rails_health_check

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  root 'welcome#index'

  resources :welcome
  resources :users
  resources :password_resets, only: %i[new create edit update]
  resources :posts do
    collection do
      get 'search', to: 'posts#search', as: :search
    end
    resources :post_details, shallow: true do
      collection do
        get 'publish'
      end
    end
    resources :comments, only: %i[create destroy]
    resource :likes, only: %i[create destroy show]
  end

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  get 'terms_of_service', to: 'pages#terms_of_service'
  get 'privacy', to: 'pages#privacy'
end
  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  belongs_to :user

  validates :user_id, presence: true
  validates :provider, presence: true
  validates :uid, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true, length: { maximum: 65_535 }
  validates :user_id, presence: true
  validates :post_id, presence: true

  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: { scope: :post_id }, presence: true
  validates :post_id, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :post_details, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  accepts_nested_attributes_for :post_details, allow_destroy: true

  enum status: { draft: 0, published: 1 }

  validates :title, presence: true
  validates :departure_date, presence: true
  validates :status, presence: true
  validates :user_id, presence: true
  validate :day_after_today

  mount_uploader :image, PostImageUploader

  belongs_to :user

  def day_after_today
    unless departure_date == nil
      errors.add(:departure_date, "は今日より前の日付を入力してください") if departure_date > Date.today
    end
  end

  def liked_by?(user)
    likes.exists?(user_id: user.id)
  end
end

app/models/post_detail.rb
class PostDetail < ApplicationRecord
  belongs_to :post

  validates :body, presence: true
  validates :arrival_at, presence: true
  validate :place_name, :address
  validates :post_id, presence: true

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  mount_uploader :image, PostDetailImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  validates :name, presence: true, uniqueness: true, length: { in: 3..20 }
  validates :email, presence: true, uniqueness: true
  validates :password, length: { in: 8..20 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :reset_password_token, presence: true, uniqueness: true, allow_nil: true

  has_many :posts, dependent: :destroy
  has_many :authentications, :dependent => :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  accepts_nested_attributes_for :authentications

  mount_uploader :avatar, AvatarUploader

  def own?(object)
    self.id == object.user_id
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @like = current_user.likes.new(post_id: @post.id)
    @like.save
  end

  def destroy
    @post = Post.find(params[:post_id])
    @like = current_user.likes.find_by(post_id: @post.id)
    @like.destroy!
  end

  def show
    @user = current_user
    @likes = Like.where(user_id: @user.id).pluck(:post_id)
    @posts = Post.find(@likes)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :require_login
  
  def terms_of_service; end
  def privacy; end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :require_login, only: [:index, :show]
  
  def index
    set_search_object
    @posts = @q.result(distinct: true).includes([:post_details, :user]).where(status: 1).order(created_at: :desc)
    @users = User.joins(:posts).where(posts: { status: 1 }).select(:name).distinct
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to new_post_post_detail_path(@post), success: t('.success')
    else
      flash.now[:danger] = t('.failure')
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @post = Post.find(params[:id])
    @post_details = @post.post_details.order(:arrival_at)
    @comment = Comment.new
    @comments = @post.comments.includes(:user).order(created_at: :desc)
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy!
    redirect_to posts_path, success: t('.success'), status: :see_other
  end

  private

  def post_params
    params.require(:post).permit(:title, :departure_date, :image, post_details_attributes: [:id, :body, :arrival_at, :image, :address, :latitude, :longitude])
  end

  def set_search_object
    @q = Post.ransack(params[:q])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]
  before_action :set_user, only: %i[edit update]

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.includes(:post_details).where(status: 1).order(created_at: :desc)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)
      redirect_to posts_path, success: t('.success')
    else 
      flash.now[:danger] = t('.failure')
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to user_path, success: t('.success')
    else
      flash.now[:danger] = t('.failure')
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar, :avatar_cache)
  end

  def set_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to login_path, flash: { danger: t('activerecord.errors.messages.require_login') }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(page_title = '')
    base_title = 'DayOutLog'
    
    page_title.empty? ? base_title : page_title + ' | ' + base_title
  end

  def default_meta_tags
    {
      site: 'DayOutLog',
      title: '1日のお出かけ記録を共有するサービス',
      reverse: true,
      charset: 'utf-8',
      description: 'DayOutLogでは散歩から旅行まで様々なお出かけ記録を時系列で投稿し、ユーザー同士で共有することができます。',
      keywords: '旅行,散歩,アウトドア,共有',
      canonical: 'https://www.dayoutlog.com/',
      separator: '|',
      og:{
        site_name: :site,
        title: :title,
        description: :description,
        type: 'website',
        url: 'https://www.dayoutlog.com/',
        image: image_url('DayOutLog_OGP.png'),
        local: 'ja-JP'
      },
      twitter: {
        card: 'summary_large_image',
        site: '@obvyamdrss',
        image: image_url('DayOutLog_OGP.png')
      }
    }
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/oauths_helper.rb
module OauthsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/post_details_helper.rb
module PostDetailsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-4VM1VPDD4Y"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'G-4VM1VPDD4Y');
    </script>
    <title><%= page_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <% if (controller.controller_name == 'post_details' && controller.action_name == 'new') || (controller.controller_name == 'posts' && controller.action_name == 'show') %>
      <meta name="turbo-visit-control" content="reload">
    <% end %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag('favicon.ico') %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
    <%= yield :css %>
    <script src="https://unpkg.com/@popperjs/core@2"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/js/bootstrap.bundle.min.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAPS_API_KEY'] %>&callback=initMap&libraries=places&v=weekly" defer></script>
    <%= javascript_importmap_tags %>
    <%= display_meta_tags(default_meta_tags) %>
  </head>

  <body>
    <% if logged_in? %>
      <%= render 'shared/header' %>
    <% else %>
      <%= render 'shared/before_login_header' %>
    <% end %>
    <%= render 'shared/flash_message' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_before_login_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg" style="background-color: #eef8f7;">
    <div class="container-fluid mx-3 my-2">
      <%= link_to image_tag("DayOutLog_header.png", width: '150'), root_path, class: 'navbar-brand' %>
      <div class="d-flex flex-row-reverse">
        <%= link_to t('header.login'), login_path, class: "btn btn-dark", role: "button" %>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_error_messages.html.erb
<% if object && object.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>">
    <%= message %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="container-fluid text-center p-3 p-md-4 bg-light sticky-bottom">
  <%= link_to image_tag("DayOutLog_背景透過(アイコン無).png", width: '150'), root_path %>
  <ul class="nav justify-content-center">
    <li class="nav-item">
      <%= link_to '利用規約', terms_of_service_path, class: "nav-link link-secondary" %>
    </li>
    <li class="nav-item">
      <%= link_to 'プライバシーポリシー', privacy_path, class: "nav-link link-secondary" %>
    </li>
    <li class="nav-item">
      <%= link_to 'お問合わせ', "https://forms.office.com/r/HGrFRDSGW4", class: "nav-link link-secondary" %>
    </li>
  </ul>
</footer>

app/views/shared/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg" style="background-color: #eef8f7;">
    <div class="container-fluid mx-3 my-2">
      <%= link_to image_tag("DayOutLog_header.png", width: '150'), posts_path, class: 'navbar-brand' %>
      <%= link_to "#", class: "navbar-toggler", type: "button", data: { bs_toggle: "collapse", bs_target: "#navbarNavDropdown" }, aria: { controls: "navbarNavDropdown", expanded: "false", label: "Toggle navigation" } do %>
        <span class="navbar-toggler-icon"></span>
      <% end %>
      <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
        <ul class="navbar-nav text-center">
          <li class="nav-item">
            <div class="nav-link active">
              <%= image_tag current_user.avatar_url, class: 'rounded-circle mr15', width: '30', height: '30', accept: 'image/*' %>
              <%= current_user.name %>
            </div>
          </li>
          <li class="nav-item"><%= link_to "マイページ", user_path(current_user), class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "いいね一覧", post_likes_path(current_user), class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "ログアウト", logout_path, class: "nav-link", data: { turbo_method: :delete } %></li>
        </ul>
      </div>
    </div>
  </nav>
</header>