config/routes.rb
Rails.application.routes.draw do
  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" 
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider
      
  get "up" => "rails/health#show", as: :rails_health_check

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  root 'welcome#index'

  resources :welcome
  resources :users
  resources :password_resets, only: %i[new create edit update]
  resources :posts do
    collection do
      get 'search', to: 'posts#search', as: :search
    end
    resources :post_details, shallow: true do
      collection do
        get 'publish'
      end
    end
    resources :comments, only: %i[create destroy]
    resource :likes, only: %i[create destroy show]
  end

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  get 'terms_of_service', to: 'pages#terms_of_service'
  get 'privacy', to: 'pages#privacy'
end
  

app/models/post.rb
class Post < ApplicationRecord
  has_many :post_details, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  accepts_nested_attributes_for :post_details, allow_destroy: true

  enum status: { draft: 0, published: 1 }

  validates :title, presence: true
  validates :departure_date, presence: true
  validates :status, presence: true
  validates :user_id, presence: true
  validate :day_after_today

  mount_uploader :image, PostImageUploader

  belongs_to :user

  def day_after_today
    unless departure_date == nil
      errors.add(:departure_date, "は今日より前の日付を入力してください") if departure_date > Date.today
    end
  end

  def liked_by?(user)
    likes.exists?(user_id: user.id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :require_login, only: [:index, :show]
  
  def index
    set_search_object
    @posts = @q.result(distinct: true).includes([:post_details, :user]).where(status: 1).order(created_at: :desc)
    @users = User.joins(:posts).where(posts: { status: 1 }).select(:name).distinct
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to new_post_post_detail_path(@post), success: t('.success')
    else
      flash.now[:danger] = t('.failure')
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @post = Post.find(params[:id])
    @post_details = @post.post_details.order(:arrival_at)
    @comment = Comment.new
    @comments = @post.comments.includes(:user).order(created_at: :desc)
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy!
    redirect_to posts_path, success: t('.success'), status: :see_other
  end

  private

  def post_params
    params.require(:post).permit(:title, :departure_date, :image, post_details_attributes: [:id, :body, :arrival_at, :image, :address, :latitude, :longitude])
  end

  def set_search_object
    @q = Post.ransack(params[:q])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.erb
<div class="col-sm-12 col-lg-4 mb-3">
  <div id="post-id-<%= post.id %>">
    <div class="card">
      <%= link_to post, class: "card-body" do %>
        <%= image_tag post.image.url, width: "300", height: "300", style: "object-fit: cover;", class: "card-img-top img-responsive" %>
        <div class="card-body">
          <ul class="list-inline">
            <li>
              <h4 class="card-title fw-bold"><%= post.title %></h4>
            </li>
            <li>
              <p class="card-subtitle text-body-secondary"><%= l post.created_at, format: :time %></p>
            </li>
            <li class="card-text">
              <i class="fas fa-heart" aria-hidden="true"></i>
              <%= post.likes.count %>
            </li>
          </ul>
          <ul class="list-inline d-flex mb-1">
            <li class="list-inline-item">
              <%= image_tag post.user.avatar_url, class: 'rounded-circle mr15', width: '20', height: '20' %>
            </li>
            <li class="list-inline-item">
              <%= "#{post.user.name}" %>
            </li>
          </ul>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<% content_for :css do %>
	<%= stylesheet_link_tag 'posts' %>
<% end %>
<% content_for(:title, t('.title')) %>
<div class="container pt-3">
  <div class="row">
    <div class="d-grid gap-2 col-6 mx-auto">
      <%= link_to posts_path, class: 'btn btn-outline-secondary', data: { bs_toggle: "modal", bs_target: "#searchModal" } do %>
        <i class="fa-solid fa-magnifying-glass">投稿を検索</i>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <div class="row">
        <% if @posts.present? %>
          <h1 class="fw-bold fs-3 my-3">記事一覧</h1>
          <%= render @posts %>
        <% else %>
          <h1 class="fw-bold fs-3 my-3">記事一覧</h1>
          <div class="mb-3">投稿がありません</div>
        <% end %>
        <% if !current_user.nil? %>
          <%= link_to "＋", new_post_path, class: "new_post_button" %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="searchModal" tabindex="-1" aria-labelledby="searchModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="searchModalLabel">投稿を検索</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= search_form_for @q, url: posts_path do |f| %>
					<%= f.label :user_name_cont, 'ユーザー名' %>
					<%= f.search_field :user_name_cont, class: 'form-control mb-3', list: "userDatalistOptions" %>
					<datalist id="userDatalistOptions">
						<% @users.each do |user| %>
							<option value="<%= user.name %>">
						<% end %>
					</datalist>
          <%= f.label :title_or_post_details_body_cont, '投稿タイトル' %>
          <%= f.search_field :title_cont, class: 'form-control mb-3', list: "titleDatalistOptions" %>
					<datalist id="titleDatalistOptions">
						<% @posts.each do |post| %>
							<option value="<%= post.title %>">
						<% end %>
					</datalist>
          <%= f.label :post_details_address_cont, '行き先(地名、施設名など)' %>
          <%= f.search_field :post_details_address_cont, class: 'form-control mb-3' %>
          <div class="d-grid gap-2 d-md-flex justify-content-md-end">
            <%= f.submit '検索', class: 'btn btn-success' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<% content_for(:title, t('.title')) %>
<div class="container py-5">
  <div class="row">
    <div class="col-lg-8 offset-lg-2 my-5">
      <h1 class="fw-bold fs-3 text-center"><%= t('.title') %></h1>
      <%= form_with model: @post, class: "new_post", local: true do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <div class="mb-3">
          <%= f.label :title, "タイトル [必須]" %>
          <%= f.text_field :title, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :departure_date, "出発日 [必須]" %>
          <%= f.date_field :departure_date, class: "form-control" %>
        </div>
        <div class="mb-3">
          <%= f.label :image %>
          <%= f.file_field :image, class: "form-control" %>
        </div>
        <div class="d-grid gap-2 col-6 mx-auto my-2">
          <%= f.submit "行き先を追加", class: "btn btn-success" %>
        </div>
        <div class="d-grid gap-2 col-6 mx-auto my-2">
          <%= link_to "キャンセル", posts_path, class: "btn btn-outline-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<% content_for(:title, @post.title) %>
<div class="container pt-3">
  <div class="row">
    <div class="col-lg-9 offset-lg-2 my-5">
      <% if @post.image.present? %>
        <div class="text-center ratio ratio-16x9 mb-4">
          <%= image_tag @post.image.url, width: "100%", height: "auto", style: "object-fit: cover;", class: "img-fluid" %>
        </div>
      <% end %>
      <ul class="list-inline d-flex mb-1">
        <li class="list-inline-item me-auto">
          <h3 style="display: inline;" class="fw-bold"><%= @post.title %></h3>
        </li>
        <% if !current_user.nil? && current_user.own?(@post) %>
          <li class="list-inline-item">
            <%= link_to "削除", post_path(@post), class: "btn btn-danger", id: "button-post-delete", data: { turbo_method: :delete, turbo_confirm: '記事を削除します。よろしいですか？' } %>
          </li>
        <% end %>
      </ul>
      <ul class="list-inline d-flex flex-row mb-3">
        <li class="list-inline-item">
          <%= link_to user_path(@post.user), class: "link-body-emphasis link-underline link-underline-opacity-0 link-underline-opacity-75-hover" do %>
            <%= image_tag @post.user.avatar_url, class: 'rounded-circle mr15', width: '20', height: '20' %>
            <%= "#{@post.user.name}" %>
          <% end %>
        </li>
        <li class="list-inline-item text-secondary"><%= l(@post.created_at, format: :time) %></li>
      </ul>
      <ul class="list-inline">
        <li class="list-inline-item">
          <%= render "likes/like_button", post: @post %>
        </li>
      </ul>
      <p class="fw-bold fs-5"><%= l @post.departure_date %></p>
      <div class="table-responsive">
        <table class="table">
          <tbody id="table-post_detail">
            <%= render @post_details, action_type: :show %>
          </tbody>
        </table>
      </div>
      <% if @post_details.any? { |post_detail| !post_detail.latitude.nil? } %>
        <div class="m-3" id='map' style="height: 400px;"></div>
        <div id="post_details_info" data-json="<%= @post_details.to_json %>" hidden></div>
      <% end %>
      <div class="my-5">
        <%= render "comments/form", comment: @comment, post: @post %>
      </div>
      <p class="fw-bold", id="comment-count"><%= @comments.count %>件のコメント</p>
      <table class="table">
        <tbody id="table-comment">
          <%= render @comments %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<script>
  var map;
  var marker = [];
  var infoWindow = [];
  var markerLatLng;
  var markerData = JSON.parse(document.getElementById("post_details_info").dataset.json);

  function initMap() {
    var geocoder = new google.maps.Geocoder()
    var bounds = new google.maps.LatLngBounds();

    map = new google.maps.Map(document.getElementById("map"), {
      center: { lat: 35.6803997, lng: 139.7690174 },
      zoom: 15,
      mapTypeId: "roadmap",
    });

    for (var i = 0; i < markerData.length; i++) {
      if (markerData[i]['latitude'] === null) {
        continue;
      }

      var id = markerData[i]['id']

      markerLatLng = new google.maps.LatLng({
        lat: markerData[i]['latitude'],
        lng: markerData[i]['longitude']
      });

      marker[i] = new google.maps.Marker({
        position: markerLatLng,
        map: map
      });

      bounds.extend (marker[i].position);

      infoWindow[i] = new google.maps.InfoWindow({
        content: markerData[i]['place_name']
      });

      markerEvent(i);
    }

    map.fitBounds (bounds);
  };

  function markerEvent(i) {
    marker[i].addListener('click', function () {
      infoWindow[i].open(map, marker[i]);
    });
  }
</script>